# frozen_string_literal: true

# PEMK dedicated server — top-level require. Assumes the load path includes both
# server/lib and the vendored protocol/ dir (see bin/pemk_server.rb).
require "pemk_wire"        # PEMK::Wire (from protocol/)
require "pemk_prng"        # PEMK::Prng (from protocol/) — D7 cross-engine battle PRNG
require "pemk_marshal_scan" # PEMK::MarshalScan (from protocol/) — a peer body read, never loaded
require "pemk/config"
require "pemk/db"
require "pemk/password"
require "pemk/accounts"
require "pemk/sessions"
require "pemk/bans"
require "pemk/characters"
require "pemk/ledger"
require "pemk/inventory"
require "pemk/item_ledger"
require "pemk/item_tiers"
require "pemk/recent_decreases"
require "pemk/monsters"
require "pemk/trades"
require "pemk/trade_deliveries"
require "pemk/world_data"
require "pemk/battle_data"
require "pemk/team_audit"
require "pemk/encounter_mint"
require "pemk/encounter_rolls"
require "pemk/catch_calc"
require "pemk/reward_calc"
require "pemk/reward_audit"
require "pemk/monster_stats"
require "pemk/battle_records"
require "pemk/trainer_battles"
require "pemk/proof_checks"
require "pemk/trainer_proofs"
require "pemk/badge_audit"
require "pemk/flag_state"
require "pemk/gift_claims"
require "pemk/gift_grants"
require "pemk/monster_blocks"
require "pemk/resim_verdicts"
require "pemk/anomaly_detector"
require "pemk/forget"
require "pemk/peer_sessions"
require "pemk/audit"
require "pemk/position_audit"
require "pemk/pickups"
require "pemk/shop_deals"
require "pemk/money_claims"
require "pemk/money_shadow"
require "pemk/money_daily"
require "pemk/plain_text"
require "pemk/rate_limiter"
require "pemk/worker_pool"
require "pemk/player_mailbox"
require "pemk/reactor"
require "pemk/server"

module PEMK
  VERSION = "0.1.0-m1"
end
